apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-users
  namespace: authelia
data:
  users_database.yml: |
    users:
      boubie:
        displayname: "Boubie"
        password: "$argon2id$v=19$m=65536,t=3,p=4$LFFYgMdXGduGWx5GVPKWRw$ydGViuoUvPb6eZwyTPNpHNiHpmQZJSC+IeY03QstLJ8"
        email: diallo.b.boubacar95@gmail.com
        groups:
          - admins
