ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    cert-manager.io/cluster-issuer: selfsigned-issuer
  certManager: true
  tls:
    enabled: true

configMap:
  authentication_backend:
    file:
      enabled: true
      path: /config/users_database.yml

  session:
    cookies:
      - domain: home.lab
        authelia_url: https://authelia.home.lab

  storage:
    local:
      enabled: true

  notifier:
    filesystem:
      enabled: true

pod:
  extraVolumes:
    - name: users
      configMap:
        name: authelia-users
  extraVolumeMounts:
    - name: users
      mountPath: /config/users_database.yml
      subPath: users_database.yml
  probes:
    liveness:
      disable: true
    readiness:
      disable: true
    startup:
      disable: true
persistence:
  enabled: true
  storageClass: local-path
  size: 1Gi
